# Generated by Django 4.1.5 on 2023-02-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creted_date',
            new_name='creatd_date',
        ),
    ]
