# Generated by Django 4.1.5 on 2023-02-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_creted_date_product_creatd_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creatd_date',
            new_name='created_date',
        ),
    ]
