# Generated by Django 4.1.5 on 2023-02-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
