# Generated by Django 4.1.5 on 2023-02-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='MultipleImages',
        ),
    ]
