# Generated by Django 4.1.5 on 2023-02-21 05:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='product_name', unique=True),
        ),
    ]
