# Generated by Django 4.1.5 on 2023-02-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('completed', 'completed'), ('Out For Shipping', 'Out For Shipping')], default='Pending', max_length=150),
        ),
    ]
